public class Coordinator extends User {
    
    public Coordinator(String userId, String name) {
        super(userId, name, "Coordinator");
    }
    
    public void createSession() {
        System.out.println("Session created by " + name);
    }
    
    public void assignUser() {
        System.out.println("User assigned by " + name);
    }
    
    public void generateReport() {
        System.out.println("Report generated by " + name);
    }
}